name: GitHub Pages SASS

on:
    push:
        branches:
            - master

permissions:
    contents: write
    id-token: write
    pull-requests: write

jobs:
    build_css:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout source Git branch
              uses: actions/checkout@v2
              with:
                  ref: master
                  fetch-depth: 10
                  submodules: true

            - name: Make destination directory for compiled CSS
              run: mkdir -vp /tmp/up08_make2.1/assets/css

            - name: Compile CSS from SCSS files
              uses: gha-utilities/sass-build@v0.5.1
              with:
                  source: assets/scss/global.scss
                  destination: /tmp/up08_make2.1/assets/css/style.css

            - name: Checkout destination Git branch
              uses: actions/checkout@v2
              with:
                  ref: master
                  fetch-depth: 1

            - name: Move compiled CSS to path within pr-pages branch
              run: mv /tmp/up08_make2.1/assets/css assets/

            - name: Add and Commit changes to pr-pages branch
              run: |
                  git config --global user.email "${GITHUB_ACTOR}@https://users.noreply.github.com/"
                  git config --global user.name "${GITHUB_ACTOR}"
                  git add assets/css/*
                  git commit -m 'Updates compiled CSS files'

            - name: Push changes
              uses: ad-m/github-push-action@master
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  branch: pr-pages
